
version: '3.8'

services:
  # Django 服務
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env  # 引用根目錄的 .env 文件

  # Vue 服務
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: ./frontend/Dockerfile
  #   container_name: vue_app
  #   ports:
  #     - "4173:4173"
  #   volumes:
  #     - ./frontend/src:/app/src       # 僅掛載源碼目錄
  #     - ./frontend/public:/app/public # 掛載 public 資料夾
  #     - ./frontend/package.json:/app/package.json # 掛載 package.json
  #     - ./frontend/vite.config.js:/app/vite.config.js # 如果有 Vite 配置檔案
  #     - /app/node_modules             # 保留容器中的 node_modules 資料夾
  #   depends_on:
  #     - backend
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: vue_app
    ports:
      - "3000:4173"
    volumes:
      - ./frontend/src:/app/src       # 僅掛載源碼目錄
      - ./frontend/public:/app/public # 掛載 public 資料夾
      - ./frontend/package.json:/app/package.json # 掛載 package.json
      - ./frontend/vite.config.js:/app/vite.config.js # 如果有 Vite 配置檔案
      - /app/node_modules             # 保留容器中的 node_modules 資料夾
    depends_on:
      - backend

  # MySQL 服務
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}  # 從 .env 引用 DATABASE_PASSWORD
      MYSQL_DATABASE: ${DATABASE_NAME}          # 從 .env 引用 DATABASE_NAME
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: