# Generated by Django 5.1.3 on 2024-11-23 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.AutoField(db_column='machine_id', primary_key=True, serialize=False)),
                ('machine_name', models.CharField(db_column='machine_name', max_length=30, unique=True)),
                ('connecting_plate', models.IntegerField(db_column='connecting_plate')),
                ('machine_amt', models.IntegerField(db_column='machine_amt')),
                ('cdatetime', models.DateTimeField(auto_now_add=True, db_column='cdatetime')),
                ('mdatetime', models.DateTimeField(auto_now=True, db_column='mdatetime')),
            ],
            options={
                'db_table': 'machine',
            },
        ),
        migrations.CreateModel(
            name='Machine_line',
            fields=[
                ('machine_line_id', models.AutoField(db_column='machine_line_id', primary_key=True, serialize=False)),
                ('machine_line_name', models.CharField(db_column='machine_line_name', max_length=30)),
                ('emp_default_amt', models.IntegerField(db_column='emp_default_amt')),
                ('cdatetime', models.DateTimeField(auto_now_add=True, db_column='cdatetime')),
                ('mdatetime', models.DateTimeField(auto_now=True, db_column='mdatetime')),
                ('machine_id', models.ForeignKey(db_column='machine_id', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='machine.machine')),
            ],
            options={
                'db_table': 'machine_line',
            },
        ),
        migrations.CreateModel(
            name='Machine_line_record',
            fields=[
                ('record_id', models.AutoField(db_column='record_id', primary_key=True, serialize=False)),
                ('production_day', models.DateField(blank=True, db_column='production_day', null=True)),
                ('machine_line_amt', models.IntegerField(db_column='machine_line_amt')),
                ('emp_amt', models.IntegerField(db_column='emp_amt')),
                ('work_hours', models.IntegerField(db_column='work_hours')),
                ('overhead_wire', models.CharField(db_column='overhead_wire', max_length=2)),
                ('ng', models.CharField(db_column='ng', max_length=2)),
                ('cdatetime', models.DateTimeField(auto_now_add=True, db_column='cdatetime')),
                ('mdatetime', models.DateTimeField(auto_now=True, db_column='mdatetime')),
                ('machine_line_id', models.ForeignKey(db_column='machine_line_id', on_delete=django.db.models.deletion.CASCADE, to='machine.machine_line')),
            ],
            options={
                'db_table': 'machine_line_record',
            },
        ),
    ]
